
package projeto;

import com.mysql.jdbc.Connection;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import projeto.UOficial.DatabaseConnection;



public class cadastro extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNickname = new javax.swing.JTextField();
        campoNome1 = new javax.swing.JTextField();
        campoUsuario = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        cadastrar = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoNickname.setBackground(new java.awt.Color(255, 255, 255));
        campoNickname.setBorder(null);
        campoNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNicknameActionPerformed(evt);
            }
        });
        getContentPane().add(campoNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 200, 40));

        campoNome1.setBackground(new java.awt.Color(255, 255, 255));
        campoNome1.setBorder(null);
        campoNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNome1ActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 271, 200, 40));

        campoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        campoUsuario.setBorder(null);
        getContentPane().add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 355, 200, 40));

        campoSenha.setBackground(new java.awt.Color(255, 255, 255));
        campoSenha.setBorder(null);
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 525, 200, 40));

        cadastrar.setBorder(null);
        cadastrar.setContentAreaFilled(false);
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 150, 40));

        login.setBorder(null);
        login.setContentAreaFilled(false);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficial/CADASTRO.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    
    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        
        //nome, nickname, usuario e senha
        
        
        String nome = campoNome1.getText();
    String nickname = campoNickname.getText();
    String usuario = campoUsuario.getText();
    String senha = campoSenha.getText();

    try (Connection conn = (Connection) DatabaseConnection.getConnection()) {
        //  para inserir na tabela cadastro2
        String queryCadastro = "INSERT INTO cadastro2 ( nome2, nickname, usuario3, senha3) VALUES (?, ?, ?, ?)";
        PreparedStatement stmtCadastro = conn.prepareStatement(queryCadastro, Statement.RETURN_GENERATED_KEYS);
        
       stmtCadastro.setString(1, nome); 
        stmtCadastro.setString(2, nickname);
        stmtCadastro.setString(3, usuario);
        stmtCadastro.setString(4, senha);

        // executa o primeiro INSERT 
        int rowsInserted = stmtCadastro.executeUpdate();
        int idcadastro = -1; // armazena o ID gerado pela primeira query

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");

           
            ResultSet generatedKeys = stmtCadastro.getGeneratedKeys();
            if (generatedKeys.next()) {
                idcadastro = generatedKeys.getInt(1); 
            }
        }

       
        if (idcadastro != -1) {
            String queryLogin = "INSERT INTO login2 (usuario2, senha2, fk_cadastro) VALUES (?, ?, ?)";
            PreparedStatement stmtLogin = conn.prepareStatement(queryLogin);

            stmtLogin.setString(1, usuario);
            stmtLogin.setString(2, senha);
            stmtLogin.setInt(3, idcadastro); 

            // executa o segundo INSERT Login2
            int rowsInsertedLogin = stmtLogin.executeUpdate();
            if (rowsInsertedLogin > 0) {
                JOptionPane.showMessageDialog(this, "Login criado com sucesso!");
                telalogin login = new telalogin();
                login.setLocationRelativeTo(null);
                login.setVisible(true);
                this.dispose();
            }
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao realizar o cadastro: " + ex.getMessage());
    }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void campoNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNome1ActionPerformed

    private void campoNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNicknameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        
        telalogin login = new telalogin();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_loginActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField campoNickname;
    private javax.swing.JTextField campoNome1;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}
